### ISSUE TITLE
registe func panic in the go1.22.0 on linux amd64

### ISSUE THREAD

**Issue by jiftle** [ebitengine/purego#222] opened 2024-04-04 01:44 UTC
1. open lib or registe func panic in the go1.22.0 on linux amd64 'fault segment', use cgo_enabled=0
2. but in the go1.20.13 is ok

```
> uname -a
Linux john-PC 5.15.77-amd64-desktop #2 SMP Thu Jun 15 16:06:18 CST 2023 x86_64 GNU/Linux
> cat /etc/os-release
PRETTY_NAME="Deepin 20.9"
NAME="Deepin"
VERSION_ID="20.9"
VERSION="20.9"
VERSION_CODENAME="apricot"
ID=Deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="https://bbs.deepin.org/"
```

**Comment by TotallyGamerJet** [comment] 2024-04-04 02:45
Could you provide the stack trace? And specifically which C function you were trying to call? Since the tests currently pass in the CI

**Comment by jiftle** [comment] 2024-04-04 05:48
i will try go test of purego

**Comment by TotallyGamerJet** [comment] 2024-04-04 15:02
> go 1.22 , change asm code align 16byte to 8byte ?

We test go 1.22 in the CI and everything passes. If you have an issue please provide a way to reproduce it

**Comment by TotallyGamerJet** [comment] 2024-06-01 21:26
@jiftle are you still having problems in which you can share a way to reproduce?

**Comment by TotallyGamerJet** [comment] 2024-06-04 16:11
> use go1.20.13,the problem is missing.

Can I close this then?

**Comment by TotallyGamerJet** [comment] 2024-08-16 02:16
Not reproducible and no response. Closing

**Closed by TotallyGamerJet** 2024-08-16 02:16 UTC
