### ISSUE TITLE
replace cgo with purego leader to wired problem.

### ISSUE THREAD

**Issue by calvin2021y** [ebitengine/purego#158] opened 2023-08-29 10:53 UTC
In this project we use purego replace cgo last week,  the build speed is improved.

From the product env,  we  get some wired issue look like some array value changed. (they are used as schema of data structure), look like race error.

revert purego to cgo seems fix the problem.

we use unsafe pointer to pass array pointer into c world and return from cgo. (no copy or keep the pointer), look like this:

```go
func testDecode(id int64, seed uint64, device uint64, flags uint32, size int32, req []byte) (err int32, resp []byte) {
	resp = make([]byte, size+32)
	var p1 = C.int32_t(len(req))
	var p2 = C.int32_t(len(resp))
	err = int32(C.testDecode(C.int64_t(id), C.uint64_t(seed), C.uint64_t(device), C.uint32_t(flags), unsafe.Pointer(&req[0]), p1, unsafe.Pointer(&resp[0]), p2, C.int32_t(1)))
	if err > 0 {
		resp = resp[0:err]
		err = 0
	} else {
		resp = nil
	}
	return
}
```

the purego version:

```go
var cDecode func(id int64, seed uint64, device uint64, flags uint32, ib unsafe.Pointer, il int32, ob unsafe.Pointer, ol int32, op int32) int32

func testDecode(id int64, seed uint64, device uint64, flags uint32, size int32, req []byte) (err int32, resp []byte) {
	resp = make([]byte, size+32)
	var p1 = int32(len(req))
	var p2 = int32(len(resp))
	err = cDecode(id, seed, device, flags, unsafe.Pointer(&req[0]), p1, unsafe.Pointer(&resp[0]), p2, 1)
	if err > 0 {
		resp = resp[0:err]
		err = 0
	} else {
		resp = nil
	}
	return
}
```

 there is other code look like this, our binary is around 70 MB. go version is `go1.20.7 linux/amd64` run at alpine.

**Comment by calvin2021y** [comment] 2023-08-29 10:56
we use purego/v0.4.0

**Comment by TotallyGamerJet** [comment] 2023-08-29 13:52
At first glance from what you've shown there doesn't appear anything wrong. However, I'd suggest using *byte instead of unsafe.Pointer for clarity although that shouldn't effect if it works or not. 

I'm going to need some more information:
- On the purego version does the error occur even when CGO_ENABLED=1?
- How are you setting the value of testDecode? RegisterFunc?
- what output are you getting and what did you expect to see? You mention the array is changing but how? Like is it a different pointer or something?
- Does the C function your calling expect the memory to be allocated in C memory?
- Is this Alpine x86_64?
- Which Go version?

Ofc if you can provided a minimal reproducible case that would be the most advantageous

**Comment by calvin2021y** [comment] 2023-08-29 14:46
Thanks for the quick reply.

>> On the purego version does the error occur even when CGO_ENABLED=1?

**Comment by TotallyGamerJet** [comment] 2023-08-30 13:27
If you can't find a reproducible case at least test if CGO_ENABLED=1 with purego still causes issues. If that fixes it then the problem is in fakecgo if it doesn't go away then the problem is in purego package.

**Comment by TotallyGamerJet** [comment] 2023-09-13 15:45
Hmm I'm surprised you were able to create stack allocations. That definitely could be the issue here. Do you have an example? I believe purego should be forcing allocations onto the heap if you're using RegisterFunc

**Comment by TotallyGamerJet** [comment] 2024-01-07 01:52
@calvin2021y does this still happen with the latest commit?

**Comment by calvin2021y** [comment] 2024-02-16 07:19
I am not able to test this, because I can not catch this error from test env(it take time and resource to duplicate). and I am not able to switch production code into this. 

I will update if I get chance to try this in future.

**Comment by TotallyGamerJet** [comment] 2024-04-06 20:30
Closing as this is currently not reproducible. If anything changes please feel free to update

**Closed by TotallyGamerJet** 2024-04-06 20:30 UTC
Labels: question
