### ISSUE TITLE
Unexpected data after calling shared library C function

### ISSUE THREAD

**Issue by ElMostafaIdrassi** [ebitengine/purego#125] opened 2023-04-08 00:59 UTC
Full repro [here](https://github.com/ElMostafaIdrassi/purego_tests).

Given the following C function exported via a linux shared library:

```
unsigned long FuncKO(unsigned long input1, char* input2,
	unsigned long* input2Len, unsigned long* input3,
	unsigned long* input4, unsigned char* input5, unsigned long* input5Len)
{
	unsigned long rv = 0;

	if (input2Len)
		LogToFile("/var/tmp/so_sample.log", "IN : input2Len=%ld\n", *input2Len);
	if (input5Len)
		LogToFile("/var/tmp/so_sample.log", "IN : input5Len=%ld\n", *input5Len);

	if (input3)
		*input3 = 0;

	if (input4)
		*input4 = 0;

	if (input2Len)
		*input2Len = 32;

	if (input5Len)
		*input5Len = 32;

	if (input3)
		*input3 = 1;

	if (input4)
		*input4 = 1;

	if (input2Len)
		LogToFile("/var/tmp/so_sample.log", "OUT: input2Len=%ld\n", *input2Len);
	if (input5Len)
		LogToFile("/var/tmp/so_sample.log", "OUT: input5Len=%ld\n", *input5Len);

	return rv;
}
```

And given the following equivalent Golang type definition (which I hope is correct):
```
type FuncKO func(
        input1 uint32,
        input2 *byte,
        input2Len *uint32,
        input3 *uint32,
        input4 *uint32,
        input5 *byte,
        input5Len *uint32,
) uint32
```

Calling the C function from Go using the aforementioned type definition with purego does not set `input5Len` to 32 as expected, it stays `0`.
```
var input1 uint32
var input2Len uint32
var imput3 uint32
var imput4 uint32
var input5Len uint32

r := funcKOProc(
        input1,
        nil,
        &input2Len,
        &imput3,
        &imput4,
        nil,
        &input5Len,
)
fmt.Printf("=== FuncKO (nil)\n")
fmt.Printf("r             = %d\n", r)
fmt.Printf("input2Len     = %d\n", input2Len)
fmt.Printf("imput3        = %d\n", imput3)
fmt.Printf("imput4        = %d\n", imput4)
fmt.Printf("input5Len     = %d\n\n", input5Len)
```

Output:
```
=== FuncKO (nil)
r             = 0
input2Len     = 32
imput3        = 1
imput4        = 1
input5Len     = 0
```

If we look at the C function logs, we find the following:
```
$ cat /var/tmp/so_sample.log 
IN: input2Len=0
IN: input5Len=0
OUT: input2Len=4294967328
OUT: input5Len=0
```

Notice `input2Len` being set to `4294967328` in C, but still holding `32` in Go, and  `input5Len` value not changing.

If we run a sample C program that loads the same shared library and calls the same function, we get the following:
```
r             = 0
input2Len     = 32
imput3        = 1
imput4        = 1
input5Len     = 32
```
and the C function logs show:
```
$ cat /var/tmp/so_sample.log 
IN: input2Len=0
IN: input5Len=0
OUT: input2Len=32
OUT: input5Len=32
```
which is the expected behavior.

I'm not sure what could be causing this ? Maybe there is a corruption somewhere ?

**Comment by TotallyGamerJet** [comment] 2023-04-08 14:35
Is this with `CGO_ENABLED=0` or 1?

**Comment by ElMostafaIdrassi** [comment] 2023-04-08 14:43
Same behavior whether I build the go sample with CGO_ENABLED=0 or with CGO_ENABLED=1.

**Comment by ElMostafaIdrassi** [comment] 2023-04-08 16:37
It appears that the order in which the C function initializes the passed arguments has an impact on whether `input5Len` is correctly set. In the repro, I've added `FuncOK` which does exactly the same thing as `FuncKO`, the only difference is that `FuncOK` initializes the args in the order they appear in the function declaration. Not sure if this is relevant or not.

**Comment by TotallyGamerJet** [comment] 2023-04-09 01:58
I was able to replicate the issue even on macOS. The cause is because `unsigned long` is not a uint32 but uint64 in Go. Making that change creates the desired output. It's important to make sure you have _exactly_ matched the signature of the C function or strange behavior like this can happen. The problem is that C is very loose with the size of its types but there is nothing purego can do about that.

I'm closing this as resolved but if you still have issues I can reopen it.

**Closed by TotallyGamerJet** 2023-04-09 01:58 UTC

**Comment by ElMostafaIdrassi** [comment] 2023-04-09 15:04
Many thanks for taking the time to look into this, really appreciate it and it actually makes sense! I switched to using `uint` instead of `uint32` and the issue seems to be resolved now.

That being said, I am facing another issue in relation to structs.

Given the following C struct:
```
typedef struct myStruct {
	const char * 	field1;
	unsigned long 	field2;
	unsigned long 	field3;
} myStruct;
```
and the following C function:
```
unsigned long FuncKO(
	myStruct * arr,
	unsigned long arrSize)
{
	if (arr && arrSize > 0)
	{
		for (unsigned long j = 0; j < arrSize; j++)
		{
			arr[j].field2 = 0;
			arr[j].field3 = j+1;
		}
	}

	return 0;
}
```

I wrote the following go code to call the C function using purego:
```
type myStruct struct {
	field1 string
	field2 uint
	field3 uint
}

type FuncKO func(
	arr []myStruct,
	arrSize uint,
) uint

var (
	mylib      uintptr
	funcKOProc FuncKO
)

func main() {
	var err error

	mylib, err = purego.Dlopen("./libmylib.so", purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		log.Fatal(err)
	}
	purego.RegisterLibFunc(&funcKOProc, mylib, "FuncKO")

	if funcKOProc == nil {
		log.Fatalf("funcKOProc() not found in libmylib\n")
		return
	}

	myStructs := make([]myStruct, 2)
	myStructs[0] = myStruct{
		field1: "hello",
	}
	myStructs[1] = myStruct{
		field1: "world",
	}
	myStructsSize := uint(2)

	funcKOProc(
		myStructs,
		myStructsSize,
	)
	fmt.Printf("=== After FuncKO \n")
	fmt.Printf("arr           = \n")
	for _, myStruct := range myStructs {
		fmt.Printf(" field1: %v\n", myStruct.field1)
		fmt.Printf(" field2: %v\n", myStruct.field2)
		fmt.Printf(" field3: %v\n", myStruct.field3)
		fmt.Printf("-------\n")
	}
	fmt.Printf("arrSize       = %v\n", myStructsSize)
}
```

When I run it, I get the following panic:
```
=== After FuncKO 
arr           = 
 field1: 
 field2: 1
 field3: 0
-------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45f97c]

goroutine 1 [running]:
fmt.(*buffer).writeString(...)
        /usr/local/go/src/fmt/print.go:108
fmt.(*fmt).padString(0xc0000061a0?, {0x0, 0x2})
        /usr/local/go/src/fmt/format.go:110 +0x245
fmt.(*fmt).fmtS(0x47d767?, {0x0?, 0xc0000afd00?})
        /usr/local/go/src/fmt/format.go:359 +0x3f
fmt.(*pp).fmtString(0x7fc59d9ee4c8?, {0x0?, 0x1?}, 0x1?)
        /usr/local/go/src/fmt/print.go:494 +0x86
fmt.(*pp).printArg(0xc0000a88f0, {0x49bc00?, 0xc000016420}, 0x76)
        /usr/local/go/src/fmt/print.go:741 +0x21e
fmt.(*pp).doPrintf(0xc0000a88f0, {0x4ae735, 0xc}, {0xc0000aff50?, 0x1, 0x1})
        /usr/local/go/src/fmt/print.go:1077 +0x387
fmt.Fprintf({0x4ce058, 0xc000014018}, {0x4ae735, 0xc}, {0xc0000aff50, 0x1, 0x1})
        /usr/local/go/src/fmt/print.go:224 +0x75
fmt.Printf(...)
        /usr/local/go/src/fmt/print.go:233
main.main()
        /home/ubuntu/purego_test/main.go:56 +0x245
```

I am not really sure why `field1` loses its content. I tried switching the type from `string` to `[]byte` just in case, but I still got the same panic.

**Comment by TotallyGamerJet** [comment] 2023-04-09 15:40
You need to use a *byte to match *char.

**Comment by ElMostafaIdrassi** [comment] 2023-04-09 15:56
That did it, thanks again for the great help!
