### ISSUE TITLE
SIGSEGV when running any test/application using go 1.21.0rc2

### ISSUE THREAD

**Issue by raff** [ebitengine/purego#140] opened 2023-06-27 19:53 UTC
This is on MacOS 13.5 / Intel (16" MacBook 2019). I have tried some of my ebiten applications, ebiten tests and purego tests and example. They all seem to fail here:

raff|main:purego$ go run examples/objc/main_darwin.go 
SIGSEGV: segmentation violation
PC=0x7ff800864b62 m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x10cbd80, 0xc0000b2000)
	/usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0000ab4b0 sp=0xc0000ab478 pc=0x1007b2b
github.com/ebitengine/purego.RegisterFunc.func1({0xc00009c3c0?, 0x2?, 0x2?})
	/Users/rsena/go/src/github.com/ebitengine/purego/func.go:212 +0xa25 fp=0xc0000ab820 sp=0xc0000ab4b0 pc=0x10cab05
reflect.callReflect(0xc00009c1b0, 0xc0000abd88, 0xc0000abc60, 0xc0000abc68)
	/usr/local/go/src/reflect/value.go:782 +0x54c fp=0xc0000abc10 sp=0xc0000ab820 pc=0x1085c0c
reflect.callReflect(0xc00009c1b0, 0xc0000abd88, 0xc0000abc60, 0xc0000abc68)
	<autogenerated>:1 +0x45 fp=0xc0000abc40 sp=0xc0000abc10 pc=0x1095a05
reflect.makeFuncStub()
	/usr/local/go/src/reflect/asm_amd64.s:47 +0x6e fp=0xc0000abd88 sp=0xc0000abc40 pc=0x1091d8e
github.com/ebitengine/purego.Dlopen({0x10fb7b0?, 0x10dafe0?}, 0x11d5348?)
	/Users/rsena/go/src/github.com/ebitengine/purego/dlfcn.go:37 +0x1f fp=0xc0000abdc0 sp=0xc0000abd88 pc=0x10c9b3f
github.com/ebitengine/purego/objc.init.0()
	/Users/rsena/go/src/github.com/ebitengine/purego/objc/objc_runtime_darwin.go:41 +0x28 fp=0xc0000abe10 sp=0xc0000abdc0 pc=0x10ce6c8
runtime.doInit1(0x11ca600)
	/usr/local/go/src/runtime/proc.go:6739 +0xd8 fp=0xc0000abf40 sp=0xc0000abe10 pc=0x10449d8
runtime.doInit(...)
	/usr/local/go/src/runtime/proc.go:6706
runtime.main()
	/usr/local/go/src/runtime/proc.go:249 +0x374 fp=0xc0000abfe0 sp=0xc0000abf40 pc=0x1037ab4
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000abfe8 sp=0xc0000abfe0 pc=0x1063661

**Comment by TotallyGamerJet** [comment] 2023-06-27 20:12
I believe this is a duplicate of #139

**Comment by raff** [comment] 2023-06-27 20:30
It's possible there is a common cause, but it fails in a slightly different way.

**Comment by TotallyGamerJet** [comment] 2023-06-27 22:18
I'll leave it open for now and we'll see if my fix for #139 fixes this too

**Comment by raff** [comment] 2023-06-27 22:22
ok, if you open a PR I will be happy to try it out.

**Closed** 2023-07-20 11:01 UTC
Labels: bug
